#ifndef CS1410_LABS_10CHARACTERCLASS_CHARACTER_H_
#define CS1410_LABS_10CHARACTERCLASS_CHARACTER_H_

namespace rose {

class Character {};

}  // namespace rose

#endif  // CS1410_LABS_10CHARACTERCLASS_CHARACTER_H_
